name: Build Docker Image

on:
  workflow_run:
    workflows: ["Build and Publish .NET Project"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download published artifact
        uses: actions/download-artifact@v4
        with:
          name: Published-App
          path: ./published

      - name: Build Docker image
        run: docker build -t product-app-image:latest .

      - name: Save Docker image as .tar
        run: docker save product-app-image:latest -o product-app-image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: DockerImage
          path: product-app-image.tar