name: Create Docker Image

on:
  push:
    branches:
     - main
  pull_request:

  Docker:
    build:
    needs: build
    
    steps:
      - name: Checkout code
        uses: action/Checkout@v4

      - name: Download published artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: published-App
          path: ./published
      
      - name:  Build Docker image
        run: docker build -t product-app-image:latest

      - name: Save Docker Image as .tar
        run: docker save product-app-image:latest -o product-app-image.tar
      
      -name: Upload Docker Artifact
       uses: actions/upload-artifact@v4
        with:
          name: ProductImage
          path: ./product-app-image.tar
