name: Build and Publish .NET Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore depedencies
        run: dotnet restore
      
      - name: Build the Project
        run: dotnet build --configuration Release --no-restore  
      
      - name: Publish Project
        run:  dotnet publish -c Release -o ./publish
      
      - name: Upload Publish folder
        uses: actions/upload-artifact@v4
        with:
          name: Published-App
          path: ./published


