name: Full CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish ./YourApp/YourApp.csproj -c Release -o ./published

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Published-App
          path: ./published

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Published-App
          path: ./published

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Save image
        run: docker save my-image:latest -o my-image.tar

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: DockerImage
          path: my-image.tar